# Generated by Django 4.1.4 on 2023-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("selling_price", models.FloatField()),
                ("discount_price", models.FloatField()),
                ("description", models.TextField()),
                ("composition", models.TextField(default="")),
                ("prodapp", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PN", "Paneer"),
                            ("CR", "Curd"),
                            ("ML", "Milk"),
                            ("LS", "Lassi"),
                            ("MS", "Milkshake"),
                            ("GH", "Ghee"),
                            ("CZ", "Cheese"),
                            ("IC", "Ice-Creams"),
                        ],
                        max_length=50,
                    ),
                ),
                ("product_image", models.ImageField(upload_to="images")),
            ],
        ),
    ]
